name: assignment8
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.10.0
  - numpy=1.22.2
  - nbconvert=6.4.5
  - python=3.10.2
  - ipython=8.1.1
  - ipython-genutils=0.2.0
  - seaborn=0.11.2
